# Generated by Django 2.2.6 on 2019-11-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyItems', '0003_auto_20191106_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigintoCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_origin', models.CharField(max_length=100)),
                ('account_copy', models.CharField(max_length=100)),
                ('pub_id_origin', models.CharField(max_length=100)),
                ('pub_id_Copy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
