# Generated by Django 2.2.6 on 2019-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyItems', '0004_auto_20191108_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='id_attributes',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='value_attributes',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
